# numpy
Linear Algebra Librarry of python 

## **_Numpy Array_**

In [1]:
import numpy as np
l=[1,2,3]
print(np.array(l))

[1 2 3]


In [2]:
metrix=[[1,2,3],[4,5,6]]
print(np.array(metrix))

[[1 2 3]
 [4 5 6]]


In [3]:
# Arrange
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(np.arange(0,11))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#reshape
print(np.arange(12).reshape(1,-1))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


### _**NumPy Operations**_

In [14]:
arr=np.arange(12)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [17]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [19]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])